export const SET_POSTS="SET_POSTS"
export const ASYNC_FETCH_POSTS="ASYNC_FETCH_POSTS"

export const CHANGE_PAGE="CHANGE_PAGE"
export const ASYNC_CHANGE_PAGE="ASYNC_CHANGE_PAGE"

export const SET_POSTS_COUNT="SET_POSTS_COUNT"

