
export const FETCH_POST_BY_PAGE="FETCH_POST_BY_PAGE"
export const FETCH_POST_BY_PAGE_SUCCEEDED="FETCH_POST_BY_PAGE_SUCCEEDED"
export const FETCH_POST_BY_PAGE_FAILED="FETCH_POST_BY_PAGE_FAILED"

export const CHANGE_PAGE="CHANGE_PAGE"
export const ASYNC_CHANGE_PAGE="ASYNC_CHANGE_PAGE"

export const SET_POSTS_COUNT="SET_POSTS_COUNT"

