
export const FETCH_POST_BY_PAGE="FETCH_POST_BY_PAGE"
export const FETCH_POST_BY_PAGE_SUCCEEDED="FETCH_POST_BY_PAGE_SUCCEEDED"
export const FETCH_POST_BY_PAGE_FAILED="FETCH_POST_BY_PAGE_FAILED"

export const FETCH_COMMENTS_BY_POST_ID="FETCH_COMMENTS_BY_POST_ID"
export const FETCH_COMMENTS_BY_POST_ID_SUCCEEDED="FETCH_COMMENTS_BY_POST_ID_SUCCEEDED"
export const FETCH_COMMENTS_BY_POST_ID_FAILED="FETCH_COMMENTS_BY_POST_ID_FAILED"


export const CHANGE_PAGE="CHANGE_PAGE"
export const ASYNC_CHANGE_PAGE="ASYNC_CHANGE_PAGE"

export const SET_POSTS_COUNT="SET_POSTS_COUNT"

export const SET_SEARCH_QUERY="SET_SEARCH_QUERY"
export const SET_SORT_VALUE="SET_SORT_VALUE"
export const RESET_SEARCH_QUERY="RESET_SEARCH_QUERY"
